import user from "../logos/user.png";
export const logo=[
    {

                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            },
            {
                image:user
            }
        
    
]
